Setup CI/CD (#1)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,267 +1,428 @@
 version: 2.1
 
+orbs:
+  slack: circleci/slack@4.1
+
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+            aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+            aws cloudformation delete-stack --stack-name "frontend-stack-${CIRCLE_WORKFLOW_ID:0:7}"
+            aws cloudformation delete-stack --stack-name "backend-stack-${CIRCLE_WORKFLOW_ID:0:7}"
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
-    parameters:
-      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
+            curl -H "token: f220e605-9bb6-4ed7-a25e-98165078f73e" --request GET "https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
+            SUCCESS=1
+            if [[ "$SUCCESS" == 1 ]]
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd /tmp/workspace/backend
+              npm install
+              npm run migrations:revert
             fi
-            
+
+  notify:
+    description: notify slack
+    steps:
+      - slack/notify:
+          event: fail
+          custom: |
+            {
+            	"blocks": [
+            		{
+            			"type": "header",
+            			"text": {
+            				"type": "plain_text",
+            				"text": "Build Failed :x:",
+            				"emoji": true
+            			}
+            		},
+            		{
+            			"type": "section",
+            			"text": {
+            				"type": "mrkdwn",
+            				"text": "Build <$CIRCLE_BUILD_URL|#$CIRCLE_BUILD_NUM> for: *$CIRCLE_JOB* failed"
+            			}
+            		}
+            	]
+            }
+
+      - slack/notify:
+          event: pass
+          custom: |
+            {
+            	"blocks": [
+            		{
+            			"type": "header",
+            			"text": {
+            				"type": "plain_text",
+            				"text": "Build Passed :white_check_mark:",
+            				"emoji": true
+            			}
+            		},
+            		{
+            			"type": "section",
+            			"text": {
+            				"type": "mrkdwn",
+            				"text": "Build <$CIRCLE_BUILD_URL|#$CIRCLE_BUILD_NUM> for: *$CIRCLE_JOB* passed"
+            			}
+            		}
+            	]
+            }
+
+
 jobs:
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [ frontend-build ]
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            cd frontend
+            npm i
+            npm run build
       - save_cache:
-          paths: [frontend/node_modules]
+          paths: [ frontend/node_modules ]
           key: frontend-build
+
+      - notify
 
   build-backend:
     docker:
       - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [ backend-build ]
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            cd backend
+            npm i
+            npm run build
       - save_cache:
-          paths: [backend/node_modules]
+          paths: [ backend/node_modules ]
           key: backend-build
+
+      - notify
 
   test-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-                
+      - checkout
+      - restore_cache:
+          keys: [ frontend-build ]
+      - run:
+          name: Front-end test
+          command: |
+            cd frontend
+            npm i
+            npm run test
+      - save_cache:
+          paths: [ frontend/node_modules ]
+          key: frontend-build
+      - notify
+
   test-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-            
+      - checkout
+      - restore_cache:
+          keys: [ backend-build ]
+      - run:
+          name: Test backend
+          command: |
+            cd backend
+            npm i
+            npm run test
+      - save_cache:
+          paths: [ backend/node_modules ]
+          key: backend-build
+      - notify
+
   scan-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [ frontend-build ]
+      - run:
+          name: frontend scan
+          command: |
+            cd frontend
+            npm audit --audit-level=critical
+            npm audit fix --audit-level=critical --force
+
+      - save_cache:
+          paths: [ frontend/node_modules ]
+          key: frontend-build
+      - notify
 
   scan-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [ backend-build ]
+      - run:
+          name: backend scan
+          command: |
+            cd backend
+            npm audit --audit-level=critical || npm audit fix --audit-level=critical --force
+
+      - save_cache:
+          paths: [ backend/node_modules ]
+          key: backend-build
+      - notify
 
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
+      - checkout
+      - run: yum install -y tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=assignment3 \
+              --stack-name "backend-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
-          name: Ensure front-end infrastructure exist
+          name: Ensure front-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=assignment3 \
+              --stack-name "frontend-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            # Your code here
-            exit 1
+            echo "$(aws ec2 describe-instances  --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} --query 'Reservations[*].Instances[*].PublicIpAddress' --output=text)" >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
+
       - persist_to_workspace:
-          root: ~/
+          root: /tmp/workspace
           paths:
-            - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+            - .circleci/ansible/inventory.txt
+      - destroy-environment
 
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
+      - image: python:3.8
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - attach_workspace:
+          at: /tmp/workspace
+      - add_ssh_keys:
+          fingerprints:
+            - "99:fd:ac:38:59:46:df:c1:e2:09:70:90:24:49:43:36"
       - run:
           name: Install dependencies
           command: |
-            # Your code here
-            exit 1
+            apt-get update
+            apt-get install -y awscli
+            pip install ansible
+            cat .circleci/ansible/inventory.txt
       - run:
           name: Configure server
           command: |
-            # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+            export ANSIBLE_HOST_KEY_CHECKING=False
+            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+
+      - destroy-environment
+      - notify
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            cd backend
+            npm i
+            npm run migrations
       - run:
           name: Send migration results to memstash
           command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+            curl -H "Content-Type: text/plain" -H "token: f220e605-9bb6-4ed7-a25e-98165078f73e" \
+            --request PUT --data "1" https://api.memstash.io/values/migration_"${CIRCLE_WORKFLOW_ID:0:7}"
+
+      - revert-migrations
+      - destroy-environment
+      - notify
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: nikolaik/python-nodejs:python3.8-nodejs14
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: /tmp/workspace
+      - run:
+          name: install aws cli
+          command: |
+            apt-get update
+            apt-get install -y awscli
+
       - run:
           name: Install dependencies
           command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
+            cd frontend
+            npm i
       - run:
           name: Deploy frontend objects
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure      
-                    
+            BACKEND_IP=$(sed -n '2p' .circleci/ansible/inventory.txt)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            cd frontend
+            npm run build
+            aws s3 cp ./dist s3://"udapeople-${CIRCLE_WORKFLOW_ID:0:7}"/ --recursive
+
+      - revert-migrations
+      - destroy-environment
+      - notify
+
   deploy-backend:
     docker:
-      # Docker image here that supports Ansible
+      - image: nikolaik/python-nodejs:python3.8-nodejs14
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "99:fd:ac:38:59:46:df:c1:e2:09:70:90:24:49:43:36"
+      - attach_workspace:
+          at: /tmp/workspace
       - run:
-          name: Install dependencies
+          name: install python and aws cli
           command: |
-            # your code here
+            apt-get update
+            apt-get install -y awscli
+            apt-get install -y rsync
+            pip install ansible
+
       - run:
           name: Deploy backend
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            export ANSIBLE_HOST_KEY_CHECKING=False
+            cat .circleci/ansible/inventory.txt
+            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
+
+      - revert-migrations
+      - destroy-environment
+      - notify
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
+      - image: circleci/node:13.8.0
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            sudo apt-get update
+            sudo apt-get install -y awscli
+
+      - attach_workspace:
+          at: /tmp/workspace
+
       - run:
-          name: Get backend url
+          name: Backend smoke test
           command: |
-            # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
+            BACKEND_IP=$(sed -n '2p' .circleci/ansible/inventory.txt)
+            echo $BACKEND_IP
+            curl "http://${BACKEND_IP}:3030/api/status"
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com"
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+
+      - revert-migrations
+      - destroy-environment
+      - notify
 
   cloudfront-update:
     docker:
-      # Docker image here that supports AWS CLI
+       - image: amazon/aws-cli
+    working_directory: /tmp/workspace
     steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
+      - checkout
+      - run: |
+          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
+          yum install jq -y
       - run:
           name: Update cloudfront distribution
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            export OldWorkflowID=$(aws cloudformation \
+                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                --no-paginate --output text)
 
-cleanup:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            export newWorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
+            echo New workflow Id: "${newWorkflowID}"
+            echo Old workflow Id: "${OldWorkflowID}"
+
+            if [[ "$CurrentWorkflowID" != "$OldWorkflowID" ]] && [[ -n "$OldWorkflowID" ]]
             then
-              # your code here
+              echo deleting old stuff
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "frontend-stack-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "backend-stack-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "cloudfront-stack-${OldWorkflowID}"
             fi
-            
+
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --tags project=assignment3 \
+            --stack-name "cloudfront-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
+
+          environment:
+            TERM: xterm-color
+
+      - destroy-environment
+      - notify
 
 workflows:
   default:
@@ -269,29 +430,24 @@ workflows:
       - build-frontend
       - build-backend
       - test-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - test-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [test-feature-branch]
+          requires: [ test-frontend, test-backend, scan-frontend, scan-backend ]
       - configure-infrastructure:
-          requires: [deploy-infrastructure]
+          requires: [ deploy-infrastructure ]
       - run-migrations:
-          requires: [configure-infrastructure]
+          requires: [ configure-infrastructure ]
       - deploy-frontend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - deploy-backend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+          requires: [ deploy-backend, deploy-frontend ]
       - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+          requires: [ smoke-test ]
